### ISSUE TITLE
Not working consistently. Am I missing something?

### ISSUE THREAD

**Issue by keithpickering** [gmrchk/swup#82] opened 2018-11-28 19:00 UTC
I set this up according to the instructions. Only option I'm using is `elements` and it's set to `['#content']`, an element that appears on every page. 

Some clicks it works, but mostly it doesn't. Seems like about 60% of the time it just gets stuck on the is-changing, is-leaving, is-rendering, and is-animating classes, leaving a blank page until it's refreshed. Regular pages work okay (they still fail sometimes), but single posts and archives fail 100% of the time. The console doesn't give me any errors, even with debug mode enabled in the swup settings.

Am I missing something? I'd really like to get this working.

**Comment by gmrchk** [comment] 2018-11-28 19:41
Hi @keithpickering,

This sounds like you're missing an animation for one or more elements that swup should wait for to finish an animation (by default any element with class `transition-*`). This means swup waits for the element to finish the animation, but animation never even starts. 

The debug mode tells you what happens. In this case, it should rather tell you what doesn't happen, and that's `animationInDone` or `animationOutDone` events. 

Please, check your CSS definitions for transitions and the elements with classes `transition-*`.

**Comment by keithpickering** [comment] 2018-11-28 19:58
@gmrchk Thanks for the reply! I think I got this fixed. The problem was that on some templates I had a wrapper element in a different position. For instance, on one page I had something like this:

```
<div id="swup" class="transition-fade">
    <section class="primary">
        <main class="main">
            <div class="wrapper">
                ...
```

And on another page, something like this:

```
<div id="swup" class="transition-fade">
    <div class="wrapper">
        <section class="primary">
            <main class="main">
                ...
```

I changed all the templates to be like the first example, and now it seems to be working. Although I'm not sure why this should make a difference, since it's all contained inside the swup element anyway. Maybe a bug?

**Comment by gmrchk** [comment] 2018-11-28 21:00
Most likely not a bug. The structure inside of a swup containers doesn't make any difference to swup, it just replaces the inner content. 

Another reason could be a container inside of a container, but that cannot happen with one container...

Maybe a structure issue - closing one tag before another or something similar, so swup cannot parse the HTML correctly? Or is it possible you fixed the issue with `transition-*` classes by accident?

In any way, I'm glad you made it work with WordPress, and it would be awesome to see a link if the site ever goes live! ...for future reference with any WP related issues.

**Closed** 2018-11-28 23:33 UTC
